### ISSUE TITLE
Bad timestamp when prepare trace

### ISSUE THREAD

**Issue by dvdfib** [sfhardman/kong-plugin-zipkin#2]
https://github.com/sfhardman/kong-plugin-zipkin/blob/636f546e6d1266da418a8d66d246f4acc063e756/kong/plugins/zipkin/zipkin.lua#L106

The value of property **timestamp** in variable **formatted_trace** would be the value of *start_time* because get problems for display bars of nested span when plugin is configured with *sample_once_every_n_requests=1* and *simulate_server=false*.

**Comment by sfhardman** [comment]
Thanks for spotting that
