### ISSUE TITLE
zipkin serviceName is the client ip

### ISSUE THREAD

**Issue by kimloong** [sfhardman/kong-plugin-zipkin#3]
when I send a request cross the kong,the zipkin show the serviceName as the client ip,not the kong server ip,by the way,how can I set the kong's serviceName

**Comment by sfhardman** [comment]
If there is an "x-consumer-username" header (e.g. one of the Kong auth plugins is used) then this will be used as the client's service name, otherwise the client IP.
The server service name will be taken from the upstream url of the proxied API
