### ISSUE TITLE
zipkin.lua also need to be mentioned here.

### ISSUE THREAD

**Issue by tetsushiawano** [sfhardman/kong-plugin-zipkin#9]
without this line i got kong.plugins.zipkin.zipkin is not found.

https://github.com/sfhardman/kong-plugin-zipkin/blob/master/kong-plugin-zipkin-0.1.0-1.rockspec#L29

**Comment by sfhardman** [comment]
Could you submit a pull request please

**Comment by tetsushiawano** [comment]
okay!
